#ifndef DBMS_TABLEDEF_H_
#define DBMS_TABLEDEF_H_

#define TABLE_HEADER_SCHEMA_BIT 1000
#define TABLE_HEADER_MAJOR_BYTE 4
#define TABLE_HEADER_PAGES_BYTE 4
#define TABLE_HEADER_TYPES_BIT 8
#define TABLE_HEADER_LENGTH_BIT 23
#define TABLE_HEADER_NULL_BIT 1
#define TABLE_HEADER_NAME_BIT 400

#define TABLE_ITEM_NULL_BIT 1
#define TABLE_ITEM_EMPTY_BYTE 4
#define TABLE_ITEM_NEXT_BYTE 4
#define TABLE_ITEM_RID_BYTE 8
#define TABLE_ITEM_INT_BYTE 4
#define TABLE_ITEM_LONGINT_BYTE 8
#define TABLE_ITEM_CHAR_BYTE 1

#endif
